// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDdLOfbS3HRYwy-mZLKCsBHuXvMRwK5KQg',
    appId: '1:384094091379:web:94c7c5bb1aba0e8352c15c',
    messagingSenderId: '384094091379',
    projectId: 'ebuy-app-5986d',
    authDomain: 'ebuy-app-5986d.firebaseapp.com',
    storageBucket: 'ebuy-app-5986d.appspot.com',
    measurementId: 'G-X49NXS2ZK9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDdLOfbS3HRYwy-mZLKCsBHuXvMRwK5KQg',
    appId: '1:384094091379:android:7c7e69ea808363da2bd206',
    messagingSenderId: '384094091379',
    projectId: 'ebuy-app-5986d',
    storageBucket: 'ebuy-app-5986d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCO8tkY0r5FhIdX7DQvRFVpMSR21ctHDbI',
    appId: '1:926858612181:ios:c48e062be0dc985352c15c',
    messagingSenderId: '926858612181',
    projectId: 'my-shop-app-399916',
    storageBucket: 'my-shop-app-399916.appspot.com',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCO8tkY0r5FhIdX7DQvRFVpMSR21ctHDbI',
    appId: '1:926858612181:ios:85bf7f7902edd9ac52c15c',
    messagingSenderId: '926858612181',
    projectId: 'my-shop-app-399916',
    storageBucket: 'my-shop-app-399916.appspot.com',
    iosBundleId: 'com.example.app.RunnerTests',
  );
}
